#management.security.enabled=false
#management:
#    cloudfoundry:
#        enabled: false
#    server:
#        port: 9001
#    security:
#        enabled:false
#接口端口
server:
  port: 8082
#监控配置 不懂什么鬼
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
      port: 9001
      servlet:
        context-path: /
      ssl:
        enabled: false
  endpoint:
    health:
      show-details: always
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lsp?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: asd1230.0
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    show-sql: true
  redis:
#    database: 1
    host: 192.168.1.163 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: asd1230.0
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
mybatis:
  typeAliasesPackage: com.lsp.helloworld
  mapperLocations: classpath:mapper/*.xml

# 打印sql
logging:
  level:
     com.lsp.helloworld.dao : debug

